default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  socket: /tmp/mysql.sock
  host: localhost

development:
  <<: *default
  database: furima_41667_development

test:
  <<: *default
  database: furima_41667_test

production:
  <<: *default
  adapter: mysql2
  database: furima_41667_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock